Code-


import { Subscription } from "rxjs";


export class AppComponent implements OnInit{
 
  private subscription: Subscription;

  ngOnInit(){
    this.subscription= this._messageService.getEmployees().subscribe((data)=>
       this.employeeList = data,
       (error) => this.errorMessage = error)
  }
  querystring = "hello";

  cancel(){
    this.subscription.unsubscribe();
  }
}


______________________________________________________


  getEmployees():Observable<any>{
        return this._http.get<any>("http://localhost:3000/employees2")
        .pipe(catchError(this.handleError))
        .pipe(retryWhen(errors => errors.pipe(delay(1000), take(20))))
        //.pipe( retryWhen(errors => errors.pipe(delay(500), take(5), concat(throwError("Giving up Retry.!")))),)
        //This will complete the whole observable after 10 attempts. If you want to error the whole observable after 10 attempts, the observable returned by the retryWhen callback must throw:
    }
    
    ________________________________________
    
    so when we unsubscribe the observable it wont g ahead and it will stop.we can check the same in console
